apiVersion: apps/v1
kind: Deployment
metadata:
  name: mon-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mon-app
  template:
    metadata:
      labels:
        app: mon-app
        env: production
        team: devops
    spec:
      containers:
      - name: mon-app
        image: inraaa/mon-app-node:latest
        imagePullPolicy: Always
        resources:
        limits:
          cpu: "0.5"
          memory: "512Mi"
        requests:
          cpu: "0.2"
          memory: "256Mi"
        ports:
        - containerPort: 3000